spring:
  profiles:
    active: dev
---
server:
  port: 8002
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aigou
      username: root
      password: zy123
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
feign:
  hystrix:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query
---
server:
  port: 8003
spring:
  application:
    name: PRODUCT-SERVICE-TEST
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aigou_test
      username: root
      password: zy123
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
feign:
  hystrix:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query
