spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  application:
    name: PLAT-SERVICE #ctrl+shift+u 转大写
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
feign:
  hystrix:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query
---
server:
  port: 8002
spring:
  application:
    name: PLAT-SERVICE-TEST #ctrl+shift+u 转大写
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
feign:
  hystrix:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query
